---
title: "김기영"
author: "김기영"
date: '2021 5 3 '
output: html_document
---
1-1. ucla 결정트리
```{r}
library(rpart)
library(caret)
library(randomForest)
library(e1071)
library(dplyr)
library(class)
ucla <- read.csv('https://stats.idre.ucla.edu/stat/data/binary.csv')
ucla$admit = factor(ucla$admit)

train_index <- createDataPartition(ucla$admit, p=0.8, list = F)
ucla_train <- ucla[train_index,]
ucla_test  <- ucla[-train_index,]
table(ucla_train$admit)
table(ucla_test$admit)
```
1-2. 모델링 / 예측 / 평가
```{r}
dtc <- rpart(admit~.,ucla_train)
pred_d <- predict(dtc, ucla_test, type = 'class')
confusionMatrix(pred_d, ucla_test$admit)
```
1-3. ucla 랜덤포레스트
```{r}
set.seed(2021)
train_index <- createDataPartition(ucla$admit, p=0.8, list = F)
ucla_train <- ucla[train_index,]
ucla_test  <- ucla[-train_index,]
```

1-4. 모델링 / 예측 / 평가
```{r}
rf <- randomForest(admit~.,ucla_train)
pred_r <- predict(rf, ucla_test, type = 'class')
confusionMatrix(pred_r, ucla_test$admit)
```
1-5. ucla SVM
```{r}
set.seed(2021)
train_index <- createDataPartition(ucla$admit, p=0.8, list = F)
ucla_train <- ucla[train_index,]
ucla_test  <- ucla[-train_index,]
```

1-6. 모델링 / 예측 / 평가
```{r}
svc <- svm(admit~., ucla_test)
pred_s <- predict(svc, ucla_test, type = 'class')
confusionMatrix(pred_s, ucla_test$admit)
```

1-7. ucla KNN
```{r}
set.seed(2021)
train_index <- createDataPartition(ucla$admit, p=0.8, list = F)
ucla_train <- ucla[train_index,]
ucla_test  <- ucla[-train_index,]
```

1-8. 모델링 / 예측 / 평가
```{r}
k <- knn(ucla_train[,1:4],ucla_test[,1:4],
         ucla_train$admit, k=3)
k

table(k)
confusionMatrix(k,ucla_test$admit)
```
2-1 wine 결정트리
```{r}
library(dplyr)
wine <- read.csv('https://raw.githubusercontent.com/KIM7751/R-Lecture-2021/main/data/wine.data.txt', sep= ",")
columns <- read.csv('https://raw.githubusercontent.com/KIM7751/R-Lecture-2021/main/data/wine.name.txt')
names(wine)
names(wine)[2:14] <- columns
names(wine)
names(wine)[2:14] <- substr(columns, 4, nchar(columns))
names(wine)[1] <- 'Y'
names(wine)
wine$Y = factor(wine$Y)

set.seed(2021)
wine_index <- createDataPartition(wine$Y, p=0.8, list = F)
wine_train  <- wine[wine_index,]
wine_test   <- wine[-wine_index,]
```

2-2 모델링 / 예측 / 평가
```{r}
dtc_w <- rpart(Y ~ ., wine_train)
pre_wd <- predict(dtc_w, wine_test, type = 'class')
confusionMatrix(pre_wd, wine_test$Y)
```
2-3 wine 랜덤포레스트
```{r}
set.seed(2021)
wine_index <- createDataPartition(wine$Y, p=0.8, list = F)
wine_train  <- wine[wine_index,]
wine_test   <- wine[-wine_index,]
```

2-4 모델링 / 예측 / 평가
```{r}
rf_w <- randomForest(Y ~ . , wine_train)
pre_wr <- predict(rf_w, wine_test, type = 'class')
confusionMatrix(pre_wr, wine_test$Y)
```
2-5 wine SVM
```{r}
set.seed(2021)
wine_index <- createDataPartition(wine$Y, p=0.8, list = F)
wine_train  <- wine[wine_index,]
wine_test   <- wine[-wine_index,]
```

2-6 모델링 / 예측 / 평가
```{r}
svc_w <- svm(Y ~ . , wine_train)
pre_ws <- predict(svc_w, wine_test , type = 'class')
confusionMatrix(pre_ws, wine_test$Y)
```
2-7 wine KNN
```{r}
library(class)
kw <- knn(wine_train[,1:14],wine_test[,1:14],
         wine_train$Y, k=3)
kw

confusionMatrix(kw, wine_test$Y)
```

