---
title: "5단원 문제"
author: "김기영"
date: '2021 4 26 '
output: html_document
---

### 단축키
- Chunk 생성: Ctrl + Alt + I
- Knit Document: Ctrl + Shift + K

1. 연도별 데이터 파일을 읽어들여 NHIS2002~NHIS2016라는 변수 이름으로 저장하라
```{r}
NHIS2002 <- read.csv('data/NHIS_OPEN_GJ_2002_v1.CSV') 
NHIS2003 <- read.csv('data/NHIS_OPEN_GJ_2003_v1.CSV') 
NHIS2004 <- read.csv('data/NHIS_OPEN_GJ_2004_v1.CSV') 
NHIS2005 <- read.csv('data/NHIS_OPEN_GJ_2005_v1.CSV') 
NHIS2006 <- read.csv('data/NHIS_OPEN_GJ_2006_v1.CSV') 
NHIS2007 <- read.csv('data/NHIS_OPEN_GJ_2007_v1.CSV') 
NHIS2008 <- read.csv('data/NHIS_OPEN_GJ_2008_v1.CSV') 
NHIS2009 <- read.csv('data/NHIS_OPEN_GJ_2009_v1.CSV') 
NHIS2010 <- read.csv('data/NHIS_OPEN_GJ_2010_v1.CSV') 
NHIS2011 <- read.csv('data/NHIS_OPEN_GJ_2011_v1.CSV') 
NHIS2012 <- read.csv('data/NHIS_OPEN_GJ_2012_v1.CSV') 
NHIS2013 <- read.csv('data/NHIS_OPEN_GJ_2013_v1.CSV') 
NHIS2014 <- read.csv('data/NHIS_OPEN_GJ_2014_v1.CSV') 
NHIS2015 <- read.csv('data/NHIS_OPEN_GJ_2015_v1.CSV')
NHIS2016 <- read.csv('data/NHIS_OPEN_GJ_2016_v1.CSV') 


```

2. 데이터 파일과 함께 다운로드된 사용자 매뉴얼 파일의 내용을 참고하여 결측값을 제거 하고 각 열의 데이터형을 알맞게 변환하여 정리하라
```{r}

```

3. 2002년 데이터에서 성별, 시도, 연령대 순으로 요약된 통계값을 구하라
```{r}
na02 <- NHIS2002 %>% select(성별코드, 시도코드, 연령대코드.5세단위.)
summary(na02)
```

4. 2003 ~ 2016년 데이터에서 3번과 같은 방법으로 요약된 통계를 구하라
```{r}
na03 <- NHIS2003 %>% select(성별코드, 시도코드, 연령대코드.5세단위.)
summary(na03)

na04 <- NHIS2004 %>% select(성별코드, 시도코드, 연령대코드.5세단위.)
summary(na04)

na05 <- NHIS2005 %>% select(성별코드, 시도코드, 연령대코드.5세단위.)
summary(na05)

na06 <- NHIS2006 %>% select(성별코드, 시도코드, 연령대코드.5세단위.)
summary(na06)

na07 <- NHIS2007 %>% select(성별코드, 시도코드, 연령대코드.5세단위.)
summary(na07)

na08 <- NHIS2008 %>% select(성별코드, 시도코드, 연령대코드.5세단위.)
summary(na08)

na09 <- NHIS2009 %>% select(성별코드, 시도코드, 연령대코드.5세단위.)
summary(na09)

na10 <- NHIS2010 %>% select(성별코드, 시도코드, 연령대코드.5세단위.)
summary(na10)

na11 <- NHIS2011 %>% select(성별코드, 시도코드, 연령대코드.5세단위.)
summary(na11)

na12 <- NHIS2012 %>% select(성별코드, 시도코드, 연령대코드.5세단위.)
summary(na12)

na13 <- NHIS2013 %>% select(성별코드, 시도코드, 연령대코드.5세단위.)
summary(na13)

na14 <- NHIS2014 %>% select(성별코드, 시도코드, 연령대코드.5세단위.)
summary(na14)

na15 <- NHIS2015 %>% select(성별코드, 시도코드, 연령대코드.5세단위.)
summary(na15)

na16 <- NHIS2016 %>% select(성별코드, 시도코드, 연령대코드.5세단위.)
summary(na16)
```

