---
title: "dplyr 연습문제"
author: "김기영"
date: '2021 4 26 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1.
```{r}
library(dplyr)
library(ggplot2)
displ_4 <- mpg %>%
    filter(displ<=4) %>%
    summarise(hwy.avg=mean(hwy))
    

displ5_ <- mpg %>%
    filter( displ>=5) %>%
    summarise(hwy.avg=mean(hwy))

displ_4 
displ5_

displ_4 > displ5_
```

2.
```{r}
audi_cty.avg <- mpg %>%
    filter(manufacturer == 'audi') %>%
    summarise(cty.avg=mean(cty))

toyota_cty.avg <-mpg %>%
    filter(manufacturer == 'toyota') %>%
    summarise(cty.avg=mean(cty))

audi_cty.avg

toyota_cty.avg

audi_cty.avg < toyota_cty.avg

```

3. 
```{r}
chevrolet_hwy.avg <- mpg %>%
    filter(manufacturer == 'chevrolet') %>%
    summarise(hwy.avg=mean(hwy))
ford_hwy.avg <- mpg %>%
    filter(manufacturer == 'ford') %>%
    summarise(hwy.avg=mean(hwy))
honda_hwy.avg <- mpg %>%
    filter(manufacturer == 'honda') %>%
    summarise(hwy.avg=mean(hwy))

total <- sum(chevrolet_hwy.avg, ford_hwy.avg, honda_hwy.avg) 

total_hwy.avg <- total/3
```

4.
```{r}
only_class_cty <- mpg %>%
    select(class, cty)

c_cdata <- glimpse(only_class_cty)
```

5.
```{r}
suv_cty.avg <- c_cdata %>%
    filter(class == 'suv') %>%
    summarise(cty.avg=mean(cty))

compact_cty.avg <- c_cdata %>%
    filter(class == 'compact') %>%
    summarise(cty.avg=mean(cty))

suv_cty.avg
compact_cty.avg

suv_cty.avg < compact_cty.avg
```

6.
```{r}
df <- mpg %>% 
    select(manufacturer, model, hwy)

sim <- glimpse(df)

sim %>% 
    filter(manufacturer == 'audi') %>%
    arrange(desc(hwy)) %>%
    head(5)
```

7.
```{r}
# -1
cop <- mpg
cop <- cop %>%
    mutate(total = cop$cty + cop$hwy)

# -2
cop <- cop %>%
    mutate(total.avg = total /2)

# -3
cop %>%
    select(class, total.avg) %>%
    arrange(desc(total.avg)) %>%
    head(3)

# -4 
mpg %>%
    mutate(total = mpg$cty + mpg$hwy) %>%
    mutate(total.avg = total / 2) %>%
    select(class, total.avg) %>%
    arrange(desc(total.avg)) %>%
    head(3)
```

8.
```{r}
mpg %>%
    group_by(class) %>%
    summarise(cty.avg=mean(cty))
```

9.
```{r}
mpg %>%
    group_by(class) %>%
    summarise(cty.avg=mean(cty)) %>%
    arrange(desc(cty.avg))
```

10.
```{r}
mpg %>%
    group_by(manufacturer) %>%
    summarise(hwy.avg=mean(hwy)) %>%
    arrange(desc(hwy.avg)) %>%
    head(3)
```

11.
```{r}
mpg %>%
    filter(class == 'compact') %>% 
    group_by(manufacturer) %>%
    summarise(counter = n()) %>% # n() - 행의 개수를 세어줌
    arrange(desc(counter))       
```


